#!/usr/bin/env bash

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Git aliases
alias gb="git branch"
alias gs="git status --short --branch"
alias gd="git diff"
alias gcm="git commit -m"
alias gca="git commit --amend"
alias gco="git checkout"
alias gfp="git fetch --prune"
alias gpl="git pull"
alias ga="git add"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit -n 10"
alias push="git push"